version: '3.3'

services:
  redis_tls_message:
    container_name: redis_tls_message
    build:
      context: ./redis-sharding/redis-tls-container/
    ports:
      - "6377:6377"
    volumes:
      - ./redis-sharding/redis-tls-container/certs:/etc/certs
